auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
schema_config:
  configs:
    - from: "2022-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
  - from: "default"
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /path/to/active/index
    cache_location: /path/to/cache

chunk_store_config:
  filesystem:
    directory: /path/to/chunks

