auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s
  max_block_bytes: 209715200  
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

compactor:
  compaction:
    block_retention: 48h

querier:
  frontend_worker:
    frontend_address: tempo:3100  
    grpc_client_config:
      max_send_msg_size: 209715200  # Increase the send message size limit to 200 MB
      max_recv_msg_size: 209715200  # Increase the receive message size limit to 200 MB

